Update check-pr.yml

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -52,30 +52,34 @@ jobs:
           REPO_OWNER="rdkcentral"
           REPO_NAME="firebolt-apis"
           WORKFLOW_NAME="MFOS standalone sanity report - CORE,MANAGE,DISCOVERY"
+          MAX_POLLS=30  # Max polls before timeout
+          POLL_INTERVAL=50  # In seconds
 
-          while true; do
-            response=$(curl -s -H "Authorization: token $TOKEN" \
-              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows" | jq \
-              --arg WORKFLOW_NAME "$WORKFLOW_NAME" \
-              '.workflows[] | select(.name == $WORKFLOW_NAME)')
-            
-            workflow_id=$(echo $response | jq -r '.id')
-            if [ "$workflow_id" == "null" ]; then
-              echo "Workflow not found, retrying in 10 seconds..."
-              sleep 10
-              continue
-            fi
+          # Fetch the workflow ID once
+          response=$(curl -s -H "Authorization: token $TOKEN" \
+            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows" | jq \
+             --arg WORKFLOW_NAME "$WORKFLOW_NAME" \
+            '.workflows[] | select(.name == $WORKFLOW_NAME)')
 
-            # Get the latest workflow run
+          workflow_id=$(echo $response | jq -r '.id')
+          if [ "$workflow_id" == "null" ]; then
+            echo "Workflow not found."
+            sleep 10
+            continue
+          fi
+
+          # Start polling for the workflow run
+          for ((i=0; i<MAX_POLLS; i++)); do
+            # Use the same response to get the latest run
             run_response=$(curl -s -H "Authorization: token $TOKEN" \
               "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$workflow_id/runs?per_page=1")
 
             status=$(echo $run_response | jq -r '.workflow_runs[0].status')
             conclusion=$(echo $run_response | jq -r '.workflow_runs[0].conclusion')
-            
+
             # Store conclusion if available
             echo "JS_SDK_CONCLUSION=$conclusion" >> $GITHUB_ENV
-            
+
             if [ "$status" == "completed" ] && [ "$conclusion" == "success" ]; then
               echo "JavaScript SDK generated successfully for the OpenRPC changes."
               break
@@ -83,10 +87,18 @@ jobs:
               echo "Failed to generate JavaScript SDK for the OpenRPC changes."
               exit 1
             else
-              echo "Still in progress. Checking again in 120 seconds..."
-              sleep 120
+              echo "Still in progress. Checking again in ${POLL_INTERVAL} seconds..."
+              sleep $POLL_INTERVAL
             fi
           done
+
+          # Final check after loop
+          if [ "$i" -eq "$MAX_POLLS" ]; then
+            echo "Timeout reached while waiting for JavaScript SDK generation."
+            exit 1
+          else
+            echo "Polling completed successfully."
+          fi
       - name: Poll Firebolt-api for CPP SDK generation
         id: poll-cpp-sdk
         run: |
@@ -95,51 +107,53 @@ jobs:
           REPO_NAME="firebolt-apis"
           PR_NUMBER="${{ github.event.pull_request.number }}"
           WORKFLOW_NAME="CXX build"
+          MAX_POLLS=30  # Max polls before timeout
+          POLL_INTERVAL=50  # In seconds
+          PR_NUMBER="${{ github.event.pull_request.number }}"
 
-          # Poll for the latest workflow run in Repo2
-          while true; do
-            # Fetch the list of workflows
-            response=$(curl -s -H "Authorization: token $TOKEN" \
-              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows" | jq \
-              --arg WORKFLOW_NAME "$WORKFLOW_NAME" \
-              '.workflows[] | select(.name == $WORKFLOW_NAME)')
+          # Fetch the workflow ID once
+          response=$(curl -s -H "Authorization: token $TOKEN" \
+            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows" | \
+            jq --arg WORKFLOW_NAME "$WORKFLOW_NAME" \
+            '.workflows[] | select(.name == $WORKFLOW_NAME)')
 
-            workflow_id=$(echo $response | jq -r '.id')
-            if [ "$workflow_id" == "null" ]; then
-              echo "Workflow not found, retrying in 10 seconds..."
-              sleep 10
-              continue
-            fi
+          workflow_id=$(echo $response | jq -r '.id')
+          if [ "$workflow_id" == "null" ]; then
+            echo "Workflow not found."
+            sleep 10
+            continue
+          fi
 
-            # Get the latest workflow run
+          # Start polling for the workflow run
+          for ((i=0; i<MAX_POLLS; i++)); do
+            # Use the same response to get the latest run
             run_response=$(curl -s -H "Authorization: token $TOKEN" \
               "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$workflow_id/runs?per_page=1")
 
-            run_id=$(echo $run_response | jq -r '.workflow_runs[0].id')
-            conclusion=$(echo $run_response | jq -r '.workflow_runs[0].conclusion')
             status=$(echo $run_response | jq -r '.workflow_runs[0].status')
-
-            # Check if the workflow run is still in progress
-            if [ "$status" != "completed" ]; then
-            echo "CPP SDK generation still in progress. Checking again in 60 seconds..."
-            sleep 60
-            continue
-            fi
-
+            conclusion=$(echo $run_response | jq -r '.workflow_runs[0].conclusion
             # Store conclusion if available
             echo "CPP_SDK_CONCLUSION=$conclusion" >> $GITHUB_ENV
 
-            # Check if the workflow completed successfully or failed
-            if [ "$conclusion" == "success" ]; then
-              echo "CPP SDK generated successfully for the OpenRPC changes."
-              # Optionally, you can add comments or further steps here
-              break  # Exit the loop on success
-            elif [ "$conclusion" == "failure" ]; then
-              echo "Warning: CPP SDK generation failed for the OpenRPC changes."
-              break  # Fail the job if the SDK generation fails
+            if [ "$status" == "completed" ] && [ "$conclusion" == "success" ]; then
+              echo "C++ SDK generated successfully for the OpenRPC changes."
+              break
+            elif [ "$status" == "completed" ] && [ "$conclusion" == "failure" ]; then
+              echo "Failed to generate C++ SDK for the OpenRPC changes."
+              exit 1
+            else
+              echo "Still in progress. Checking again in ${POLL_INTERVAL} seconds..."
+              sleep $POLL_INTERVAL
             fi
           done
 
+          # Final check after loop
+          if [ "$i" -eq "$MAX_POLLS" ]; then
+            echo "Timeout reached while waiting for C++ SDK generation."
+            exit 1
+          else
+            echo "Polling completed successfully."
+          fi
       - name: Post comments on PR
         if: env.JS_SDK_CONCLUSION != 'unknown' || env.CPP_SDK_CONCLUSION != 'unknown'  # Only run if at least one SDK ran
         run: |
