Versions

diff --git a/.github/workflows/merge-to-next-major.yml b/.github/workflows/merge-to-next-major.yml
--- a/.github/workflows/merge-to-next-major.yml
+++ b/.github/workflows/merge-to-next-major.yml
@@ -89,8 +89,14 @@ jobs:
         run: |
           jq '.version = "${{ steps.extract_version.outputs.version }}"' package.json > temp.json
 
-          mv temp.json package.json
-          git add package.json && git commit -m "Sync next->next-major package.json"
+          diff -q "package.json" "temp.json"
+
+          if [ "$?" -eq 0 ]; then
+            mv temp.json package.json
+            git add package.json && git commit -m "Sync next->next-major package.json"
+          else
+            echo "Versions are identical. No change required."
+          fi
 
       - name: Perform Merge
         run: |
